### ISSUE TITLE
Convert Measurement from json

### ISSUE THREAD

**Issue by n1vekk** [AwesomeTeamOne/3DView.Measurements#1]
I added this measurement controller in 3d editor like (https://threejs.org/editor/).
when save&load I save the string of models from the following code.
eg; var output = JSON.stringify(measurement.toJSON());
when load the measurement is not same as origin.
Is there any way to restore the measurement(obj.children) as origin?
This is special use case for me.
If you can help with this I will be appreciate.
PS: sorry for my bad english. it is somehow complex, so I can not explain as well.
if you have any question let me know.
Thank you.

**Comment by Dmitry-Luminar** [comment]
The measurement object has links to points of different objects on the scene.
When you serialize it using THREE.Measurement.export function - it stores all these points in world coordinate system without reference to original objects they belong with. 

To load this data back you must use THREE.MeasurementControls.load function that attempts to revert the original state of a measurement back

**Comment by n1vekk** [comment]
Hi Dmitry
Thank you for your help.
by the way I have one more problem.
Current we can change the position of Length measurement.
Is there any way to change the position of Angle measurement?
