### ISSUE TITLE
Polygon area measurement

### ISSUE THREAD

**Issue by n1vekk** [AwesomeTeamOne/3DView.Measurements#2]
How can I add measurement like draw polygon and measure the area and circumference?

**Comment by DmitryTrofimov32** [comment]
This is not supported unfortunately. Area measurements in 3d can be
particularly challenging.

**Comment by n1vekk** [comment]
[Measurement.Circum.zip](https://github.com/AwesomeTeamOne/3DView.Measurements/files/2797238/Measurement.Circum.zip)
Try to make draw polygon like tool that measure the circumference and area based on your library and it works for me.
I hope it will be helpful for your future work.
Thank you.
